analyse_cisco_log:
  description: >
    You extract form the log file the findings wich explain the {symptoms}
  expected_output: >
    A list of findings findings wich explain the {symptoms}.
  agent: cisco_expert

analyse_packet_capture:
  description: >
    You extract form the log file the findings wich explain the {symptoms}
  expected_output: >
    A list of findings wich explain the {symptoms}.
  agent: pcap_expert

final_report:
  description: >
    You corelate the list of findings from and created
    a detail report which explains the {symptoms} and propose remediation.
  expected_output: >
    A list detailed report.
  agent: network_engineer
